### ISSUE TITLE
DmlExecutionProvider is much slower than CPUExecutionProvider

### ISSUE THREAD

**Issue by zk-talentech** [microsoft/onnxruntime#10856]
**Describe the bug**
Model : converted from [palm_detection_tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_full.tflite?raw=true)

CPUExecutionProvider: ORT perf 4.09ms/inference
DmlExecutionProvider: ORT perf 7.86ms/inference

DML is much slower than CPU.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 22000.556
- ONNX Runtime installed from (source or binary): "pip install onnxruntime-directml" 
- ONNX Runtime version: 1.10
- Python version: 3.7
- Visual Studio version (if applicable): 2022
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: AMD Ryzen™ 7 5800H Integrated GPU
- TensorFlow version: 2.8.0

**To Reproduce**
In tensorflow-onnx repository, run:
```
python tests/run_pretrained_models.py --opset 12 --config models.yaml --tests hand_landmark_full --perf perf.txt
```
I got "**ORT perf 4.09ms/inference**".

Then modify run_pretrained_models.py to set the EP to DmlExecutionProvider, run the command again, I got "**ORT perf 7.86ms/inference**".

The content of `models.yaml` is:
```
hand_landmark_full:
  tf_min_version: 2.7
  disabled: false
  url: https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_full.tflite?raw=true
  model: hand_landmark_full.tflite
  model_type: tflite
  input_get: get_beach
  opset_constraints:
    "onnx":
      "min": 12
  inputs:
    "input_1": [1,224,224,3]
  outputs:
    - Identity
    - Identity_1
    - Identity_2
    - Identity_3
```

**Expected behavior**
DML should be faster than CPU provider.
